In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

### Creating List

In [3]:
my_list = [0, 1, 2, 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

### 1-D Array

In [6]:
# Converting  list to array
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(my_list)

list

## `np.arange(start, stop, step)`
* similar to range() function where it gives an array instead of a list
* gives an evenly spaced values with specified interval

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [15]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(20, 10) # 1st arg > 2nd arg

array([], dtype=int64)

In [20]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [21]:
np.arange(-16, 10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [22]:
ar = np.arange(-30, 20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [23]:
np.arange()

TypeError: arange() requires stop to be specified.

In [24]:
np.arange(10, 30, 5) # start, stop, step

array([10, 15, 20, 25])

In [25]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [28]:
np.arange(10, 30, 5, 8) # max 3 argument can be pass in arange()

TypeError: Cannot interpret '8' as a data type

## `np.zeros( shape, dtype)`
* Use to creating an array with specified shape and datatype with all the element filled with zeros
* shape:
  * for 1-D array we use only one element like np.zeros(10)
  * for 2-D array we use a tuple like np.zeros((2, 2))
* dtype: int, float

In [85]:
np.zeros(10) # parameter tuning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros(10, dtype=int) # hyperparameter tuning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

`2-D Array`

In [33]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [35]:
zero = np.zeros([2,2])
print(zero)

print("___________________")

print(type(zero))

[[0. 0.]
 [0. 0.]]
___________________
<class 'numpy.ndarray'>


In [36]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
np.zeros((10, 10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## `np.ones(shape, dtype)`
* Use to create an array with specified shape and datatype with all the element filed with ones.
* shape:
  * for 1-D array we use only one element like np.zeros(10)
  * for 2-D array we use a tuple like np.zeros((2, 2))
* dtype: int, float

In [38]:
np.ones(3)

array([1., 1., 1.])

In [39]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [41]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# np.random 

## `np.random.rand(rows, column)`
* It creates an array of specified shape and populate with random float numbers
* if one argument then only column will take
* if two argument then 1st will be row and 2nd will be column

In [45]:
import random

In [51]:
random.rand(2,3)

AttributeError: module 'random' has no attribute 'rand'

In [86]:
random.randint(10, 30)

30

In [87]:
random.random()

0.7807492677643696

In [48]:
np.random.rand(2,3)

array([[0.65982039, 0.37511189, 0.57650751],
       [0.42579496, 0.32277368, 0.49889422]])

In [52]:
np.random.rand(5)

array([0.64248463, 0.01109981, 0.95661866, 0.34528521, 0.3918712 ])

In [54]:
np.random.rand(3, 5)

array([[0.78180204, 0.95027989, 0.75996809, 0.82797489, 0.54518545],
       [0.54912073, 0.89456665, 0.39016794, 0.30178344, 0.38069784],
       [0.93972253, 0.41059533, 0.79645251, 0.4423218 , 0.94692445]])

## `np.random.randint(low, high, size)`
* low: takes lowest number compare to high
* high: takes highest number compare to low
* size: array size
  * one integer for 1D array
  * two integer for 2D array
* dtype: int, float

In [55]:
np.random.randint(4, 6)

5

In [56]:
np.random.randint(2, 20, 4) # 2nd argument is exclusive

array([18, 17, 15,  3], dtype=int32)

In [59]:
np.random.randint(30, 20, 10) # 1st argument > 2nd argument

ValueError: low >= high

In [60]:
np.random.randint(-30, 20, 10)

array([  6, -26,  16, -28, -24, -11,  -8, -30,   4,  17], dtype=int32)

In [63]:
np.random.randint(-30, 20, 10, 5)

TypeError: Cannot interpret '5' as a data type

In [65]:
np.random.randint(10, 40, (10, 10)) # 10x10 matrix

array([[25, 36, 30, 32, 31, 27, 37, 23, 37, 18],
       [34, 26, 17, 24, 22, 33, 33, 29, 19, 27],
       [13, 12, 36, 24, 16, 37, 14, 36, 26, 36],
       [10, 22, 18, 39, 18, 33, 11, 33, 35, 32],
       [32, 28, 26, 16, 13, 20, 26, 30, 30, 29],
       [24, 23, 15, 26, 38, 37, 20, 35, 34, 34],
       [11, 17, 18, 33, 22, 18, 37, 21, 21, 14],
       [29, 32, 39, 27, 27, 22, 26, 37, 38, 14],
       [29, 39, 29, 18, 19, 26, 30, 28, 24, 26],
       [39, 30, 12, 12, 23, 12, 24, 20, 22, 34]], dtype=int32)

In [66]:
np.random.randint(1, 100, (12, 12)) # 12x12 matrix

array([[ 2, 49, 54, 13, 75, 76, 40, 51, 50, 39, 25, 28],
       [22, 67, 13,  3, 54, 51, 93, 78, 12, 95, 21, 74],
       [17,  9, 75, 75, 37, 43, 86, 22, 76, 26, 31, 95],
       [92, 51, 89, 67, 29, 62, 89, 69, 79, 12, 53, 58],
       [16, 79, 23, 57, 98, 52, 33, 62, 58,  4, 82, 88],
       [47, 93, 36, 31, 14, 43, 35, 80, 32, 76, 91, 90],
       [65, 88, 75, 17,  9, 54, 38, 57, 50, 25, 73,  9],
       [12, 64, 36, 85, 98, 89, 25, 83, 19, 69, 83,  6],
       [88, 39, 74, 62, 49, 61,  1, 82, 11, 70, 90, 39],
       [10, 31, 68, 51, 38, 71, 39, 80, 97, 25, 18, 61],
       [38, 99, 97, 91, 45, 34, 71, 65, 64,  9, 23, 35],
       [72,  3, 20,  1, 37, 23, 24, 16,  5, 48,  1, 67]], dtype=int32)

## `.reshape(row, column)`
* Changing the shape of an array without altering the data

In [67]:
arr

array([0, 1, 2, 3, 4, 5])

In [68]:
np.arange(1, 13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [88]:
np.arange(1,13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
np.arange(1, 13).reshape(1, 16)

ValueError: cannot reshape array of size 12 into shape (1,16)

In [75]:
np.arange(1, 13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [76]:
np.arange(1, 13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

## `Slicing in matrix`

In [77]:
b = np.random.randint(10, 20, (5, 4))
b

array([[12, 13, 16, 16],
       [13, 14, 14, 12],
       [15, 16, 18, 11],
       [10, 10, 12, 10],
       [16, 14, 18, 19]], dtype=int32)

In [78]:
type(b)

numpy.ndarray

In [80]:
b[:]

array([[12, 13, 16, 16],
       [13, 14, 14, 12],
       [15, 16, 18, 11],
       [10, 10, 12, 10],
       [16, 14, 18, 19]], dtype=int32)

In [81]:
b[0]

array([12, 13, 16, 16], dtype=int32)

In [84]:
b[0][3]

np.int32(16)