# 1. Array Creation Functions

In [1]:
import numpy as np

In [2]:
# Create an array fraom a list
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [5]:
# Create an array with evenly space values
b = np.arange(0, 10, 2)
print("Array b:", b)

Array b: [0 2 4 6 8]


In [6]:
# Create an array filled with zeroes
d = np.zeros((2,3))
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Create an array filled with ones
e = np.ones((3,2))
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# create an identity matrix
f = np.eye(4) # 4x4 idntity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [9]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3)) # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [10]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (3, 1)) # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [ ]:
# Flatten an array (means converting to one vector)
f1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
flattened = np.ravel(f1) # Flatten to 1D array
print("flattened array:", flattened)

flattened array: [1 2 3 4 5 6 7 8]


In [13]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1) # Transpose the array
print("Transposed array: \n", transposed)

Transposed array: 
 [[1 3]
 [2 4]]


In [ ]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2]) # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]
