# Creating Numpy array

In [1]:
import numpy as np

In [2]:
np.array([2, 4, 56, 422, 32, 1]) # 1D Array

array([  2,   4,  56, 422,  32,   1])

In [3]:
a = np.array([2, 4, 56, 422, 32, 1])
print(a)

[  2   4  56 422  32   1]


In [4]:
type(a)

numpy.ndarray

In [5]:
new = np.array([[45, 34, 22, 2], [24, 55, 3, 22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [7]:
# 3D Array # Tensor
np.array([[2, 3, 33, 4, 45], [23, 45, 56, 66, 2], [357, 523, 32, 34, 2], [23, 32, 44, 33, 234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  34,   2],
       [ 23,  32,  44,  33, 234]])

## dtype
* The desired data-type for the array. If not given then the type willbe determined as the minimum type required to hold the object in the sequence.

In [8]:
np.array([11, 23, 44], dtype=float)

array([11., 23., 44.])

In [9]:
np.array([11, 23, 44], dtype=bool) # Here True becoz, python treats Non-zero as True

array([ True,  True,  True])

In [11]:
np.array([11, 23, 44], dtype=complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

## Numpy Array Vs Python Seqences
* NumPy arrays have a fixed size at creation, unilike python lists(which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The element in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using python's built in sequences.

* A growing plethora of scientific and mathematical python-based packages are using NumPy array; though these typically support python-sequence input, they convert such input to Numpy Arrays prior to processing, and they often output NumPy arays.

## arange

arange can be called with a varying number of positional arguments

In [12]:
np.arange(1, 25) # from 1 - 24 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [13]:
np.arange(1, 25, 2) # strides--> alternate numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

## reshape 
Both of number products should be equal to number of items present inside the array

In [14]:
np.arange(1, 11).reshape(5,2) # converted 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
np.arange(1,11).reshape(2,5) #converted 2 rows and 5 coulumns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
np.arange(1, 13).reshape(3,4) # converted 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Ones and Zeros
You can initialize the values and create values. ex: in deep learning weight shape

In [20]:
# np.ones and np.zeros
np.ones((3,4)) # we have to mention inside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# another type ---> random()
np.random.random((4,3))

array([[0.66071226, 0.54278794, 0.4935543 ],
       [0.23525824, 0.71318558, 0.82965164],
       [0.52439257, 0.15716262, 0.76418503],
       [0.54705435, 0.42709934, 0.08687002]])

## linspace
It is also called as Linearly space, Linearly separable, in a given range at equal distnace it creates points.

In [24]:
np.linspace(-10, 10, 10) # here: lower range, upper range, number of items to generate

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## identity
Indentity matrix is that diagonal items will be ones and everything will be zeros

In [25]:
# Creating the indentity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Array Attributes

In [28]:
a1 = np.arange(10) # 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a2 = np.arange(12, dtype=float).reshape(3,4) # Matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [30]:
a3 = np.arange(8).reshape(2,2,2) # 3D ==> Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## ndim
To findout given arrays number of dimensions

In [31]:
a1.ndim

1

In [32]:
a2.ndim

2

In [33]:
a3.ndim

3

## Size
gives number of items

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a3.size # it has 8 items. like shape : 2,2,2 = 8

8

In [36]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [37]:
a2.size 

12

## items size
memory occumpied by the items

In [38]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1.itemsize # bytes

8

In [40]:
a2.itemsize

8

In [41]:
a3.itemsize

8

## dtype
gives data type of the item

In [42]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


## Changing Data Type

In [43]:
# astype
x = np.array([33, 22, 2.5])
x

array([33. , 22. ,  2.5])

In [44]:
x.astype(int)

array([33, 22,  2])

## Array operations

In [46]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12, 24).reshape(3,4)

In [47]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Scalar Operations
Scalar oprations on Numpy arrays include performing addition or subtraction, or multiplication on each element of a Numpy array.

In [49]:
# arihmetic
z1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [50]:
# subtraction
z1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [51]:
# Multiplication
z1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [52]:
# Modulo
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

## relational Operators
The relational operators are also known as comparison operators, their main function is to return either a true or false based on the values of operands.

In [53]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
z2 > 2 # if 2 is greater than everything gives True

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

## Vector Operation
We can apply on both numpy array

In [56]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
# Arithmatic
z1 + z2 #both numpy array shape is same, we can add item wise

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [59]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [60]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [61]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

## Array Functions

In [64]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[53., 90., 53.],
       [35., 85., 77.],
       [59., 84., 37.]])

In [65]:
# Max
np.max(k1)

np.float64(90.0)

In [66]:
# min
np.min(k1)

np.float64(35.0)

In [67]:
# sum
np.sum(k1)

np.float64(573.0)

In [68]:
# prod ---> Multiplication
np.prod(k1)

np.float64(1.0619521918929e+16)

## In Numpy 
* 0 = column
* 1 = row

In [69]:
# if we want maximum of every row
np.max(k1, axis=1)

array([90., 85., 84.])

In [70]:
# maximum of every column
np.max(k1, axis=0)

array([59., 90., 77.])

In [71]:
# product of every column
np.prod(k1, axis=0)

array([109445., 642600., 150997.])

## statistics related functions

In [72]:
# mean
k1

array([[53., 90., 53.],
       [35., 85., 77.],
       [59., 84., 37.]])

In [73]:
np.mean(k1)

np.float64(63.666666666666664)

In [74]:
# mean of every coulumn
k1.mean(axis=0)

array([49.        , 86.33333333, 55.66666667])

In [75]:
# median
np.median(k1)

np.float64(59.0)

In [76]:
np.median(k1, axis=1)

array([53., 77., 59.])

In [77]:
# Standard deviation
np.std(k1)

np.float64(19.78214683327705)

In [78]:
np.std(k1, axis=0)

array([10.19803903,  2.62466929, 16.43843734])

In [80]:
np.std(k1, axis=1)

array([17.44196727, 21.92917894, 19.20069443])

In [79]:
# Variance
np.var(k1)

np.float64(391.33333333333326)

## Indexing and slicing

In [81]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [82]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Indexing on 1D array

In [85]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
# fetching last item
p1[-1]

np.int64(9)

In [87]:
# fetching fist item
p1[0]

np.int64(0)

### Indexing on 2d Array

In [88]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
# fetching desired element: 6
p2[1,2] #here 1 = row(second), 2 = column(third), because it starts from zero

np.int64(6)

In [90]:
# fetching desired element : 11
p2[2,3] # row = 2, column = 3

np.int64(11)

In [91]:
# fetching desired element : 4
p2[1, 0] # row = 1, column = 0

np.int64(4)

### Indexing on 3D (Tensors)

In [92]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
# fetching desired element: 5
p3[1, 0, 1]

np.int64(5)

EXPLANATION :Here 3D is consists of 2 ,2D array , so Firstly we take 1 because our desired is 5 is in second matrix which is 1 .and 1 row so 0 and second column so 1 

In [94]:
# fetching desired element: 2
p3[0, 1, 0]

np.int64(2)

In [95]:
# fetching desired elemtn : 0
p3[ 0, 0, 0]

np.int64(0)

In [96]:
# fetching desired element: 6
p3[1, 1, 0]

np.int64(6)

## Slicing
Fetching Multiple items

### Slicing on 1D

In [97]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
# fetching desired elemtn are: 2,3 4
p1[2:5]

array([2, 3, 4])

Explation: Here first we take, whatever we need first item, 2 and up last(4) + 1 which is 5 because last element is not included

In [99]:
# Alternate (same as python)
p1[2:5:2]

array([2, 4])

### Slicing on 2D

In [100]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
p2[0, :]

array([0, 1, 2, 3])

Explation: Here 0 represents first row and (:) represents Total column

In [102]:
# fetching total third column
p2[:, 2]

array([ 2,  6, 10])

Explation: Heere want all rows so (:), we want 3rd column so 2

In [103]:
# fetch 5, 6 and 9, 10
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
p2[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [106]:
# fetch 0,3 and 8,11
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
p2[0:3, 0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
p2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [109]:
# fetch 1, 3 and 9, 11
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
p2[0::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [111]:
# fetch only 4, 7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
p2[1:2, 0::3]

array([[4, 7]])

In [114]:
# fetch 1,2,3 and 5,6,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
p2[0:2, 1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [116]:
# fetch 1, 3 and 5,7
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
p2[0:2, 1::2]

array([[1, 3],
       [5, 7]])