In [3]:
import numpy as np

In [4]:
np.__version__

'2.1.3'

### Creating List

In [5]:
my_list = [0, 1, 2, 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

### 1-D Array

In [7]:
# Converting  list to array
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

## `np.arange(start, stop, step)`
* similar to range() function where it gives an array instead of a list
* gives an evenly spaced values with specified interval

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [13]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20, 10) # 1st arg > 2nd arg

array([], dtype=int64)

In [16]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-16, 10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [18]:
ar = np.arange(-30, 20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [19]:
np.arange()

TypeError: arange() requires stop to be specified.

In [20]:
np.arange(10, 30, 5) # start, stop, step

array([10, 15, 20, 25])

In [21]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [22]:
np.arange(10, 30, 5, 8) # max 3 argument can be pass in arange()

TypeError: Cannot interpret '8' as a data type

## `np.zeros( shape, dtype)`
* Use to creating an array with specified shape and datatype with all the element filled with zeros
* shape:
  * for 1-D array we use only one element like np.zeros(10)
  * for 2-D array we use a tuple like np.zeros((2, 2))
* dtype: int, float

In [23]:
np.zeros(10) # parameter tuning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros(10, dtype=int) # hyperparameter tuning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

`2-D Array`

In [25]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [26]:
zero = np.zeros([2,2])
print(zero)

print("___________________")

print(type(zero))

[[0. 0.]
 [0. 0.]]
___________________
<class 'numpy.ndarray'>


In [27]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros((10, 10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## `np.ones(shape, dtype)`
* Use to create an array with specified shape and datatype with all the element filed with ones.
* shape:
  * for 1-D array we use only one element like np.zeros(10)
  * for 2-D array we use a tuple like np.zeros((2, 2))
* dtype: int, float

In [29]:
np.ones(3)

array([1., 1., 1.])

In [30]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [31]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# np.random 

## `np.random.rand(rows, column)`
* It creates an array of specified shape and populate with random float numbers
* if one argument then only column will take
* if two argument then 1st will be row and 2nd will be column

In [32]:
import random

In [33]:
random.rand(2,3)

AttributeError: module 'random' has no attribute 'rand'

In [34]:
random.randint(10, 30)

24

In [35]:
random.random()

0.6275622321985799

In [36]:
np.random.rand(2,3)

array([[0.76450492, 0.29374819, 0.12473224],
       [0.36050237, 0.95391464, 0.00723225]])

In [37]:
np.random.rand(5)

array([0.00420344, 0.06328442, 0.93961924, 0.37906493, 0.49254592])

In [38]:
np.random.rand(3, 5)

array([[0.84727829, 0.44124125, 0.79187655, 0.98317582, 0.50934011],
       [0.40466593, 0.66356672, 0.8515597 , 0.66063477, 0.56894571],
       [0.29780322, 0.54493631, 0.67972944, 0.26977591, 0.08942215]])

## `np.random.randint(low, high, size)`
* low: takes lowest number compare to high
* high: takes highest number compare to low
* size: array size
  * one integer for 1D array
  * two integer for 2D array
* dtype: int, float

In [39]:
np.random.randint(4, 6)

4

In [40]:
np.random.randint(2, 20, 4) # 2nd argument is exclusive

array([ 7,  3, 19, 17], dtype=int32)

In [41]:
np.random.randint(30, 20, 10) # 1st argument > 2nd argument

ValueError: low >= high

In [42]:
np.random.randint(-30, 20, 10)

array([-12,   0, -29, -22, -29,   2, -30, -28,   9,   4], dtype=int32)

In [43]:
np.random.randint(-30, 20, 10, 5)

TypeError: Cannot interpret '5' as a data type

In [44]:
np.random.randint(10, 40, (10, 10)) # 10x10 matrix

array([[24, 34, 38, 30, 34, 33, 14, 35, 39, 22],
       [10, 21, 14, 36, 21, 38, 36, 36, 34, 20],
       [33, 35, 13, 38, 21, 15, 35, 27, 35, 16],
       [29, 14, 29, 26, 23, 27, 21, 36, 20, 38],
       [20, 20, 18, 33, 31, 27, 39, 28, 13, 23],
       [19, 24, 14, 29, 24, 34, 39, 25, 27, 39],
       [18, 24, 25, 13, 12, 17, 32, 19, 36, 31],
       [30, 36, 10, 19, 14, 36, 14, 15, 38, 22],
       [17, 12, 21, 38, 38, 38, 29, 20, 27, 34],
       [27, 31, 31, 35, 10, 24, 39, 33, 31, 11]], dtype=int32)

In [45]:
np.random.randint(1, 100, (12, 12)) # 12x12 matrix

array([[14, 59, 17, 56, 11, 56, 35, 42, 37,  6, 57, 81],
       [88, 25, 57, 68, 22, 71, 97,  7,  3, 57, 24, 39],
       [72, 21, 30,  1, 60,  8, 69, 63, 50, 37,  9, 72],
       [42, 86, 78, 70, 15, 59, 57, 17, 89,  3, 69, 49],
       [13, 81, 43, 44, 14, 65, 70, 56, 58, 53,  9, 40],
       [12, 57, 10, 81, 13, 83, 30, 53,  4, 24, 63, 59],
       [66,  8, 79,  1, 94, 84, 78, 26, 48, 19, 10, 74],
       [38, 66, 10, 96, 37, 22, 14, 35,  7, 61, 71, 42],
       [55, 59, 39, 51, 42, 33, 40, 64, 69, 56, 40, 99],
       [49, 89, 44, 85, 56, 25, 75, 25,  4, 60, 66, 54],
       [98, 90,  6, 23, 62, 44, 65, 85, 67, 61, 38, 44],
       [27, 17, 86, 14, 49, 45, 52, 95, 33, 40, 73, 25]], dtype=int32)

## `.reshape(row, column)`
* Changing the shape of an array without altering the data

In [46]:
arr

array([0, 1, 2, 3, 4, 5])

In [47]:
np.arange(1, 13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
np.arange(1,13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
np.arange(1, 13).reshape(1, 16)

ValueError: cannot reshape array of size 12 into shape (1,16)

In [51]:
np.arange(1, 13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [52]:
np.arange(1, 13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

## `Slicing in matrix`

In [53]:
b = np.random.randint(10, 20, (5, 4))
b

array([[12, 17, 18, 18],
       [19, 19, 18, 18],
       [15, 18, 14, 19],
       [16, 13, 18, 15],
       [12, 19, 10, 17]], dtype=int32)

In [54]:
type(b)

numpy.ndarray

In [55]:
b[:]

array([[12, 17, 18, 18],
       [19, 19, 18, 18],
       [15, 18, 14, 19],
       [16, 13, 18, 15],
       [12, 19, 10, 17]], dtype=int32)

In [56]:
b[0]

array([12, 17, 18, 18], dtype=int32)

In [57]:
b[0][3]

np.int32(18)

In [58]:
b

array([[12, 17, 18, 18],
       [19, 19, 18, 18],
       [15, 18, 14, 19],
       [16, 13, 18, 15],
       [12, 19, 10, 17]], dtype=int32)

In [59]:
b[1:3]

array([[19, 19, 18, 18],
       [15, 18, 14, 19]], dtype=int32)

In [60]:
b[1,3]

np.int32(18)

In [61]:
b[0,3]

np.int32(18)

In [62]:
b[1:2]

array([[19, 19, 18, 18]], dtype=int32)

In [63]:
b[1,-1]

np.int32(18)

In [64]:
b[0:-2]

array([[12, 17, 18, 18],
       [19, 19, 18, 18],
       [15, 18, 14, 19]], dtype=int32)

In [65]:
b

array([[12, 17, 18, 18],
       [19, 19, 18, 18],
       [15, 18, 14, 19],
       [16, 13, 18, 15],
       [12, 19, 10, 17]], dtype=int32)

In [66]:
b[-5, 3]

np.int32(18)

In [67]:
b[-5, -3]

np.int32(17)

# Operations

In [68]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[11, 23, 59, 26, 30, 94, 30, 52, 33, 94],
       [63, 99, 59, 26, 63, 31, 19, 60, 24, 38],
       [94, 89, 58, 30,  1,  8, 43, 38, 80, 60],
       [67, 40, 38, 20, 81, 23, 30, 58, 89, 41],
       [ 4, 63, 41, 58, 50,  0, 50,  8, 50, 66],
       [10, 90, 32, 48, 24, 82, 12, 21, 12, 83],
       [50, 31, 33, 37, 88, 59, 41, 26,  1, 32],
       [42, 78, 94, 75, 20, 98, 26, 49, 23, 58],
       [59, 49, 90, 48, 78, 90, 42, 31, 14, 46],
       [32, 93, 62, 91, 12, 19, 63, 99, 23, 14]], dtype=int32)

In [69]:
arr

array([0, 1, 2, 3, 4, 5])

In [70]:
arr[:4]

array([0, 1, 2, 3])

In [71]:
arr2

array([[11, 23, 59, 26, 30, 94, 30, 52, 33, 94],
       [63, 99, 59, 26, 63, 31, 19, 60, 24, 38],
       [94, 89, 58, 30,  1,  8, 43, 38, 80, 60],
       [67, 40, 38, 20, 81, 23, 30, 58, 89, 41],
       [ 4, 63, 41, 58, 50,  0, 50,  8, 50, 66],
       [10, 90, 32, 48, 24, 82, 12, 21, 12, 83],
       [50, 31, 33, 37, 88, 59, 41, 26,  1, 32],
       [42, 78, 94, 75, 20, 98, 26, 49, 23, 58],
       [59, 49, 90, 48, 78, 90, 42, 31, 14, 46],
       [32, 93, 62, 91, 12, 19, 63, 99, 23, 14]], dtype=int32)

In [72]:
arr2[::2]

array([[11, 23, 59, 26, 30, 94, 30, 52, 33, 94],
       [94, 89, 58, 30,  1,  8, 43, 38, 80, 60],
       [ 4, 63, 41, 58, 50,  0, 50,  8, 50, 66],
       [50, 31, 33, 37, 88, 59, 41, 26,  1, 32],
       [59, 49, 90, 48, 78, 90, 42, 31, 14, 46]], dtype=int32)

In [73]:
arr2[::-1]

array([[32, 93, 62, 91, 12, 19, 63, 99, 23, 14],
       [59, 49, 90, 48, 78, 90, 42, 31, 14, 46],
       [42, 78, 94, 75, 20, 98, 26, 49, 23, 58],
       [50, 31, 33, 37, 88, 59, 41, 26,  1, 32],
       [10, 90, 32, 48, 24, 82, 12, 21, 12, 83],
       [ 4, 63, 41, 58, 50,  0, 50,  8, 50, 66],
       [67, 40, 38, 20, 81, 23, 30, 58, 89, 41],
       [94, 89, 58, 30,  1,  8, 43, 38, 80, 60],
       [63, 99, 59, 26, 63, 31, 19, 60, 24, 38],
       [11, 23, 59, 26, 30, 94, 30, 52, 33, 94]], dtype=int32)

In [74]:
arr2[::-2]

array([[32, 93, 62, 91, 12, 19, 63, 99, 23, 14],
       [42, 78, 94, 75, 20, 98, 26, 49, 23, 58],
       [10, 90, 32, 48, 24, 82, 12, 21, 12, 83],
       [67, 40, 38, 20, 81, 23, 30, 58, 89, 41],
       [63, 99, 59, 26, 63, 31, 19, 60, 24, 38]], dtype=int32)

In [75]:
arr2[::-3]

array([[32, 93, 62, 91, 12, 19, 63, 99, 23, 14],
       [50, 31, 33, 37, 88, 59, 41, 26,  1, 32],
       [67, 40, 38, 20, 81, 23, 30, 58, 89, 41],
       [11, 23, 59, 26, 30, 94, 30, 52, 33, 94]], dtype=int32)

In [76]:
arr2[0:5:3]

array([[11, 23, 59, 26, 30, 94, 30, 52, 33, 94],
       [67, 40, 38, 20, 81, 23, 30, 58, 89, 41]], dtype=int32)

In [77]:
arr

array([0, 1, 2, 3, 4, 5])

In [78]:
arr.mean()

np.float64(2.5)

In [79]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

* '*' means import all the function internally

In [80]:
from numpy import *

In [81]:
median(arr)

np.float64(2.5)

# Indexing